name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: build/libs/my-project-0.0.1-SNAPSHOT.jar

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew test

  lint:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew lint

  sonarcloud:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: sonarsource/sonarcloud-github-action@master
        with:
          sonarcloud-organization: my-organization
          sonarcloud-project-key: my-project-key

  deploy:
    runs-on: ubuntu-latest
    needs:
      - sonarcloud
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-ecs@v1
      - uses: aws-actions/ecs-deploy@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          ecs-cluster: my-cluster
          ecs-service: my-service
          image: my-image
          image-tag: ${{ steps.build.outputs.artifact_tag }}
